//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 07:00:16 PM IST 
//


package com.devops.model.jenkins.item.mavenmoduleset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hudson.model.Queue-Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hudson.model.Queue-Item"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{}hudson.model.Actionable"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="blocked" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="buildable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="inQueueSince" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="params" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stuck" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="task" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="why" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.model.Queue-Item", propOrder = {
    "blocked",
    "buildable",
    "id",
    "inQueueSince",
    "params",
    "stuck",
    "task",
    "url",
    "why"
})
public class HudsonModelQueueItem
    extends HudsonModelActionable
{

    protected boolean blocked;
    protected boolean buildable;
    protected long id;
    protected long inQueueSince;
    protected String params;
    protected boolean stuck;
    protected Object task;
    protected String url;
    protected String why;

    /**
     * Gets the value of the blocked property.
     * 
     */
    public boolean isBlocked() {
        return blocked;
    }

    /**
     * Sets the value of the blocked property.
     * 
     */
    public void setBlocked(boolean value) {
        this.blocked = value;
    }

    /**
     * Gets the value of the buildable property.
     * 
     */
    public boolean isBuildable() {
        return buildable;
    }

    /**
     * Sets the value of the buildable property.
     * 
     */
    public void setBuildable(boolean value) {
        this.buildable = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the inQueueSince property.
     * 
     */
    public long getInQueueSince() {
        return inQueueSince;
    }

    /**
     * Sets the value of the inQueueSince property.
     * 
     */
    public void setInQueueSince(long value) {
        this.inQueueSince = value;
    }

    /**
     * Gets the value of the params property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParams() {
        return params;
    }

    /**
     * Sets the value of the params property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParams(String value) {
        this.params = value;
    }

    /**
     * Gets the value of the stuck property.
     * 
     */
    public boolean isStuck() {
        return stuck;
    }

    /**
     * Sets the value of the stuck property.
     * 
     */
    public void setStuck(boolean value) {
        this.stuck = value;
    }

    /**
     * Gets the value of the task property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getTask() {
        return task;
    }

    /**
     * Sets the value of the task property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTask(Object value) {
        this.task = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the why property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhy() {
        return why;
    }

    /**
     * Sets the value of the why property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhy(String value) {
        this.why = value;
    }

}
