//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 07:00:16 PM IST 
//


package com.devops.model.jenkins.item.mavenmoduleset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hudson.model.Executor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hudson.model.Executor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="currentExecutable" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="currentWorkUnit" type="{}hudson.model.queue.WorkUnit" minOccurs="0"/&gt;
 *         &lt;element name="idle" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="likelyStuck" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="progress" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hudson.model.Executor", propOrder = {
    "currentExecutable",
    "currentWorkUnit",
    "idle",
    "likelyStuck",
    "number",
    "progress"
})
public class HudsonModelExecutor {

    protected Object currentExecutable;
    protected HudsonModelQueueWorkUnit currentWorkUnit;
    protected boolean idle;
    protected boolean likelyStuck;
    protected int number;
    protected int progress;

    /**
     * Gets the value of the currentExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCurrentExecutable() {
        return currentExecutable;
    }

    /**
     * Sets the value of the currentExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCurrentExecutable(Object value) {
        this.currentExecutable = value;
    }

    /**
     * Gets the value of the currentWorkUnit property.
     * 
     * @return
     *     possible object is
     *     {@link HudsonModelQueueWorkUnit }
     *     
     */
    public HudsonModelQueueWorkUnit getCurrentWorkUnit() {
        return currentWorkUnit;
    }

    /**
     * Sets the value of the currentWorkUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link HudsonModelQueueWorkUnit }
     *     
     */
    public void setCurrentWorkUnit(HudsonModelQueueWorkUnit value) {
        this.currentWorkUnit = value;
    }

    /**
     * Gets the value of the idle property.
     * 
     */
    public boolean isIdle() {
        return idle;
    }

    /**
     * Sets the value of the idle property.
     * 
     */
    public void setIdle(boolean value) {
        this.idle = value;
    }

    /**
     * Gets the value of the likelyStuck property.
     * 
     */
    public boolean isLikelyStuck() {
        return likelyStuck;
    }

    /**
     * Sets the value of the likelyStuck property.
     * 
     */
    public void setLikelyStuck(boolean value) {
        this.likelyStuck = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     */
    public int getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     */
    public void setProgress(int value) {
        this.progress = value;
    }

}
