//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 07:00:16 PM IST 
//


package com.devops.model.jenkins.item.mavenmoduleset;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hudson.model.BallColor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="hudson.model.BallColor"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="red"/&gt;
 *     &lt;enumeration value="red_anime"/&gt;
 *     &lt;enumeration value="yellow"/&gt;
 *     &lt;enumeration value="yellow_anime"/&gt;
 *     &lt;enumeration value="blue"/&gt;
 *     &lt;enumeration value="blue_anime"/&gt;
 *     &lt;enumeration value="grey"/&gt;
 *     &lt;enumeration value="grey_anime"/&gt;
 *     &lt;enumeration value="disabled"/&gt;
 *     &lt;enumeration value="disabled_anime"/&gt;
 *     &lt;enumeration value="aborted"/&gt;
 *     &lt;enumeration value="aborted_anime"/&gt;
 *     &lt;enumeration value="notbuilt"/&gt;
 *     &lt;enumeration value="notbuilt_anime"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "hudson.model.BallColor")
@XmlEnum
public enum HudsonModelBallColor {

    @XmlEnumValue("red")
    RED("red"),
    @XmlEnumValue("red_anime")
    RED_ANIME("red_anime"),
    @XmlEnumValue("yellow")
    YELLOW("yellow"),
    @XmlEnumValue("yellow_anime")
    YELLOW_ANIME("yellow_anime"),
    @XmlEnumValue("blue")
    BLUE("blue"),
    @XmlEnumValue("blue_anime")
    BLUE_ANIME("blue_anime"),
    @XmlEnumValue("grey")
    GREY("grey"),
    @XmlEnumValue("grey_anime")
    GREY_ANIME("grey_anime"),
    @XmlEnumValue("disabled")
    DISABLED("disabled"),
    @XmlEnumValue("disabled_anime")
    DISABLED_ANIME("disabled_anime"),
    @XmlEnumValue("aborted")
    ABORTED("aborted"),
    @XmlEnumValue("aborted_anime")
    ABORTED_ANIME("aborted_anime"),
    @XmlEnumValue("notbuilt")
    NOTBUILT("notbuilt"),
    @XmlEnumValue("notbuilt_anime")
    NOTBUILT_ANIME("notbuilt_anime");
    private final String value;

    HudsonModelBallColor(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HudsonModelBallColor fromValue(String v) {
        for (HudsonModelBallColor c: HudsonModelBallColor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
